### PR TITLE
Make calls to kubernetes more resilient

### PR DESCRIPTION
**Pull request by JAORMX**
In case there are issues with the deployment, we retry (with backoff).

This also adds the necessary bits in the Makefile to push this image to
the cluster to be able to easily test this.

### CODE REVIEW

**Comment by jhrozek** [comment]
Two questions:
1. Shouldn't we have a maximum number of tries? The library seems to [support that](https://godoc.org/github.com/cenkalti/backoff#WithMaxRetries)
2. Have you considered using `k8s.io/client-go/util/retry` instead to just keep using k8s deps?

**Comment by JAORMX** [comment]
> Two questions:
> 
>     1. Shouldn't we have a maximum number of tries? The library seems to [support that](https://godoc.org/github.com/cenkalti/backoff#WithMaxRetries)
I'm using the default. What do you suggest the maximum be?
> 
>     2. Have you considered using `k8s.io/client-go/util/retry` instead to just keep using k8s deps?
I did initially. We don't have it available in the client-go version we're using.

**Comment by jhrozek** [comment]
On Wed, Dec 11, 2019 at 08:24:20AM -0800, Juan Osorio Robles wrote:
> > Two questions:
> > 
> >     1. Shouldn't we have a maximum number of tries? The library seems to [support that](https://godoc.org/github.com/cenkalti/backoff#WithMaxRetries)
> I'm using the default. What do you suggest the maximum be?

Does the default ever stop or does it keep trying? I'm mostly concerned
about cases that can never recover like the CM already existing.

Looking at the docs of backoff.NewExponentialBackOff() is it not clear
to me if there's an upper limit.

> > 
> >     2. Have you considered using `k8s.io/client-go/util/retry` instead to just keep using k8s deps?
> I did initially. We don't have it available in the client-go version we're using.

OK

**Comment by JAORMX** [comment]
@jhrozek OK, proposed something to being with (15).

**Comment by jhrozek** [comment]
Thank you, 15 is as good as any number.
The code looks good, the built image passed compliance-operator e2e tests and the newly added makefile targets all seem to work.

**Pull request merged**
